### ISSUE TITLE
Some craftable gear renders improperly (or not at all)

### ISSUE THREAD

**Issue by ghost** [Arkay-1248/Do-Not-Go-Gentle#13]
**Upload your crashlog**

N/A

**Required: Modlist.txt**

[modlist.txt](https://github.com/Arkay-1248/Do-Not-Go-Gentle/files/9736179/modlist.txt)

**Describe the bug**

1. "Elven Steel (Battle Mage)" gear is invisible
2. "Royal Elven" gear is invisible
3. "Cyrodilic Iron Falchion" has a broken texture

**To Reproduce**

Just give yourself the smithing perks with the console and enter `coc qasmoke` to try a convenient forge in-game.

**Expected behavior**
The items to display normally. Or, if the invisible gear isn't intended to be playable, it shouldn't be in the crafting menu.

**Screenshots**

![cyrodilic iron falchion bug](https://user-images.githubusercontent.com/102565812/194622474-b0f3e1b4-1322-48a5-9385-14475dd1bb4c.jpg)

**Modlist version**

1.0.2

**Did you add any additional mods?**

No

**Comment by Arkay-1248** [comment]
Cyrodilic Iron Falchion has a broken texture because of the BS_Bruma mod not giving it any textures. I cannot fix that even though I tried. The other two mentioned are not invisible in the world or on a character, only in the crafting menu, so I don't think I need to fix that. I'll update the mods if the authors do though.
